[theme]

# Primary accent for interactive elements
primaryColor = '#0A75BC'

# Background color for the main content area

backgroundColor = '#231f20'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#FCE029'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "monospace"

[server]
enableCORS = false